# Generated by Django 5.2.15 on 2026-07-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("host", "Host")],
                default="student",
                max_length=20,
            ),
        ),
    ]
